- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Install requirements
  yum:
    name:
      - gcc
      - pcre-devel
      - tar
      - make
    state: present

- name: Download file from a file path
  ansible.builtin.get_url:
    url: "http://www.haproxy.org/download/{{ haproxy_version }}/src/haproxy-{{ haproxy_version }}.{{ haproxy_patch_version }}.tar.gz"
    dest: /root/haproxy