- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Install requirements
  yum:
    name:
      - gcc
      - pcre-devel
      - tar
      - make
    state: present

- name: Download file from a file path
  ansible.builtin.get_url:
    url: "http://www.haproxy.org/download/{{ haproxy_version }}/src/haproxy-{{ haproxy_version }}.{{ haproxy_patch_version }}.tar.gz"
    dest: /root

- name: Extract haproxy.tar.gz into /root/haproxy
  ansible.builtin.unarchive:
    src: "/root/haproxy-{{ haproxy_version }}.{{ haproxy_patch_version }}.tar.gz"
    dest: "/root"
    remote_src: yes

- name: Install haproxy
  command: "bash -lc 'cd /root/haproxy-{{ haproxy_version }}.{{ haproxy_patch_version }} && make TARGET=linux-glibc && make install'"

- name: Creates haproxy config directory
  file:
    path: "/etc/haproxy"
    state: directory

- name: Create haproxy library directory
  file:
    path: "/var/lib/haproxy"
    state: directory

- name: Create haproxy library stats file
  file:
    path: "/var/lib/haproxy/stats"
    state: file

- name: Create daemon config
  command: "cp /root/haproxy-{{ haproxy_version }}.{{ haproxy_patch_version }}/examples/haproxy.init /etc/init.d/haproxy"

- name: Change mod for daemon config
  command: "chmod 755 /etc/init.d/haproxy"

- name: Change mod for daemon config
  command: "chmod 755 /etc/init.d/haproxy"

- name: Daemon reload
  command: "systemctl daemon-reload"

- name: Daemon autorestart
  command: "chkconfig haproxy on"
